services:
    Pipirima\PimcoreCsvExportColumnsBundle\EventListener\CsvExportListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.dataobject.postCsvItemExport, method: onPostCsvItemExport }
